ChatApp/urls.py
from django.urls import path
from . import views



app_name = 'chat'

urlpatterns = [
    path('', views.create_room, name='create_room'),
    path('<str:room_name>/<str:username>/', views.massage_view, name='room'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ChatApp.urls', namespace='chat')),
]

ChatApp/models.py
from django.db import models

# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
    message = models.TextField()
    sender = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.room.name

ChatApp/views.py
from django.shortcuts import render, redirect
from .models import Room, Message


def create_room(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        room_name = request.POST.get('room')

        try:
            get_room = Room.objects.get(name=room_name)
        except Room.DoesNotExist:
            new_room = Room(name=room_name)
            new_room.save()
        return redirect('chat:room', room_name=room_name, username=username)
    return render(request, 'index.html')


def massage_view(request, room_name, username):
    get_room = Room.objects.get(name=room_name)
    messages = Message.objects.filter(room=get_room)
    context = {
        'room_name': get_room,
        'messages': messages,
        'user': username,
    }
    return render(request, 'message.html', context)

templates/_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Messages</title>
    <!-- load static -->
    {% load static %}
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}"> -->
    <!-- link to h=css file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <div class="parent">
        <div class="child-2">
            <center><h2>Chats</h2></center><hr>
            <div class="chat-body-parent">
                <div class="chat-body" id="tasks">
                    <div class="message" id="chatContainer">
                      <!-- received messages and displayed here -->
                        
                            
                                <div class="receive">
                                    <p style="color: #000;"> {{i.message}}<strong>-{{i.sender}}</strong></p>
                                </div>
                            
                                <div class="send">
                                    <p style="color: #000;">{{i.message}}</p>
                                </div>
                            
                    <!-- end receive messages -->
                    </div>

                    <div class="form">
                        <form action="" id="message-form" method="POST">
                            {% csrf_token %}
                            <textarea id="msg" cols="30" name="message" rows="10" placeholder="Enter your message" required></textarea>
                            <button class="submit" type="submit">Send</button>
                        </form>    
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script>
    function scrollToBottom() {
        var chatContainer = document.getElementById("chatContainer");
        chatContainer.scrollTop = chatContainer.scrollHeight;
    }


</script>
<style>

* {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    }


    .parent {
      background-color: #B1A296;
    }

    nav {
        display: flex;
        justify-content: space-around;
        align-items: center;
        background-color: #659DBD;
        padding: 10px;
    }

    nav ul li {
        list-style: none;
        display: inline-block;
        padding: 10px;
    }

    nav ul li:hover {
        background-color: dodgerblue;
        color: #fff;
        transition: 0.8s;
    }

    nav ul li a {
        text-decoration: none;
        color: #fff;
    }

    .parent {
        height: 100vh;
        display: flex;
        justify-content: center;
        /* background-image: url("/static/img/bck.jpg");  */
       
        background-position: center; 
        background-repeat: no-repeat; 
        background-size: cover; 
        align-items: center;
        width: 100%;
    }

    .child-1 {
        /* height: 70vh; */
        width: 30%;
        margin: 10px;
        border-radius: 10px;
        
        background-color: white;
    }

    .chat-room {
        width: 100%;
        /* max-height: ; */
        border-radius: 10px;
        display: flex;
        align-items: center;
        justify-content: space-around;
        background-color: #fff;
        border: 1px solid dodgerblue;
    }

    .profile-pic {
        /* height: 80px; */
        width: 15%;
        
        border-radius: 50px;
        background-color: #fff;
    }

    .profile-pic img {
        width:100%;
        height:100%;
        border-radius: 50%;
        object-fit: cover;
    }

    .chat-room h3 {
        color: #000;
    }

    .chat-room h3 {
        background-color: gray;
        padding: 10px;
        border-radius: 5px;
        text-decoration: none;
    }

    .chat-room h3 a {
        text-decoration: none;
        color: white;
    }


    .child-2 {
        /* max-height: 100vh; */
        width: 50%;
        margin: 10px;
        border-radius: 10px;
        padding: 10px;
        background-color: #FBEEC1;
    }

    .chat-body-parent {
        display: flex;
        justify-content: center;
        align-items: center;
        /* height: 60vh; */
    }

    .chat-body, .message {
        /* max-height: 100vh; */
        width: 100%;
        background-color: #557A95;
        border-radius: 10px;
        display: flex;      
        padding: 10px;
        flex-direction: column;
    }

    .message {
        max-height: 400px;  /* Or whatever height value you see fit */
        overflow-y: auto;
    }

    .chat-body .message .receive, .send {
        background-color: #B1A296;
        max-width: 400px;
       
        border-radius: 10px;
        padding: 10px;
        margin-bottom: 10px;
    }

    .send:hover {
        padding: 15px;
        transition: 0.8s;
    }

    .receive:hover {
        padding: 15px;
        transition: 0.8s;
    }

    .chat-body .message .send {
        align-self: flex-end;
    }

    .chat-body .message .receive {
        align-self: flex-start;
    }

    form {
        display: flex;
        align-items: center;
        justify-content: space-around;
    }

    form textarea {
        width: 70%;
        height: 40px;
        border-radius: 10px;
        padding: 10px;
    }

    form button {
        width: 25%;
        padding: 10px;
        background-color: #FBEEC1;
        border-radius: 5px;
        border: none;
        color: #000;
    }
    @media only screen and (max-width: 600px) {
    .child-2 {
        width: 100%;
    }
}

</style>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enter Room</title>
</head>
<body>
    <div class="parent">
        <div class="child">
            <h1>Enter Room</h1>
            <form action="{% url 'chat:create_room' %}" method="POST">
                {% csrf_token %}
                <label for="">Username</label><br>
                <input type="text" placeholder="Username" name="username" required><br>
                <label for="">Room name</label><br>
                <input type="text" placeholder="room name" name="room" required><br>
                <center><button type="submit">Submit</button></center><br>
            </form>
        </div>
    </div>
</body>
<style>

* {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}

.parent {
    background-color: #DAAD86;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
}

.child {
    display: flex;
    background-color: #659DBD;
    height: 80vh;
    width: 50%;
    border-radius: 10px;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin: 100px;
}

form {
    width: 80%;
}

input {
    padding: 10px;
    border: 1px solid dodgerblue;
    width: 100%;
    margin: 10px;
    border-radius: 5px;
}

button {
    background-color: #DAAD86;
    padding: 10px;
    color: white;
    border: none;
    border-radius: 5px;
    width: 20%;
}

button:hover {
    padding: 15px;
    transition: 0.8s;
}
</style>
</html>

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Messages</title>
    <!-- load static -->
    {% load static %}
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}"> -->
    <!-- link to h=css file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <div class="parent">
        <div class="child-2">
            <center><h2>Chats</h2></center><hr>
            <div class="chat-body-parent">
                <div class="chat-body" id="tasks">
                    <div class="message" id="chatContainer">
                      <!-- received messages and displayed here -->
                        {% for i in messages %}
                            {% if i.sender != user %}
                                <div class="receive">
                                    <p style="color: #000;"> {{i.message}}<strong>-{{i.sender}}</strong></p>
                                </div>
                            {% else %}
                                <div class="send">
                                    <p style="color: #000;">{{i.message}}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    <!-- end receive messages -->
                    </div>

                    <div class="form">
                        <form action="" id="message-form" method="POST">
                            {% csrf_token %}
                            <textarea id="msg" cols="30" name="message" rows="10" placeholder="Enter your message" required></textarea>
                            <button class="submit" type="submit">Send</button>
                        </form>    
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script>
    function scrollToBottom() {
        var chatContainer = document.getElementById("chatContainer");
        chatContainer.scrollTop = chatContainer.scrollHeight;
    }

    const websocketProtocol = window.location.protocol === "https:" ? "wss" : "ws";
    const wsEndpoint = `${websocketProtocol}://${window.location.host}/ws/notification/{{room_name}}/`;
    const socket = new WebSocket(wsEndpoint);

    document.getElementById('message-form').addEventListener('submit', function(event){
        event.preventDefault();
        const message = document.getElementById('msg').value;
        socket.send(
            JSON.stringify({
                'message': message,
                'room_name': '{{room_name}}',
                'sender': '{{user}}',
            })
        )
    });

    // response from consumer on server
    socket.addEventListener("message", (event) => {
    const messageData = JSON.parse(event.data)['message'];
    console.log(messageData);

    var sender = messageData['sender'];
    var message = messageData['message'];

    // empty message input field after message has been sent
    if (sender == '{{ user|escapejs }}') { // تأكد أن القيم يتم استبدالها بشكل صحيح
        document.getElementById('msg').value = '';
    }

    // Here's where we append the message to the chatbox.
    var messageDiv = document.querySelector('.message');
    if (sender != '{{ user|escapejs }}') { // تأكد من التوافق مع نفس القيمة
        messageDiv.innerHTML += '<div class="receive"><p style="color: #000;">' + message + '<strong>-' + sender + '</strong></p></div>';
    } else {
        messageDiv.innerHTML += '<div class="send"><p style="color: #000;">' + message + '</p></div>';
    }
    scrollToBottom();
});


    socket.onopen = (event) => {
        console.log("WebSocket connection opened!");
    };

    socket.onclose = (event) => {
        console.log("WebSocket connection closed!");
    };

</script>
<style>

* {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    }


    .parent {
      background-color: #B1A296;
    }

    nav {
        display: flex;
        justify-content: space-around;
        align-items: center;
        background-color: #659DBD;
        padding: 10px;
    }

    nav ul li {
        list-style: none;
        display: inline-block;
        padding: 10px;
    }

    nav ul li:hover {
        background-color: dodgerblue;
        color: #fff;
        transition: 0.8s;
    }

    nav ul li a {
        text-decoration: none;
        color: #fff;
    }

    .parent {
        height: 100vh;
        display: flex;
        justify-content: center;
        /* background-image: url("/static/img/bck.jpg");  */
       
        background-position: center; 
        background-repeat: no-repeat; 
        background-size: cover; 
        align-items: center;
        width: 100%;
    }

    .child-1 {
        /* height: 70vh; */
        width: 30%;
        margin: 10px;
        border-radius: 10px;
        
        background-color: white;
    }

    .chat-room {
        width: 100%;
        /* max-height: ; */
        border-radius: 10px;
        display: flex;
        align-items: center;
        justify-content: space-around;
        background-color: #fff;
        border: 1px solid dodgerblue;
    }

    .profile-pic {
        /* height: 80px; */
        width: 15%;
        
        border-radius: 50px;
        background-color: #fff;
    }

    .profile-pic img {
        width:100%;
        height:100%;
        border-radius: 50%;
        object-fit: cover;
    }

    .chat-room h3 {
        color: #000;
    }

    .chat-room h3 {
        background-color: gray;
        padding: 10px;
        border-radius: 5px;
        text-decoration: none;
    }

    .chat-room h3 a {
        text-decoration: none;
        color: white;
    }


    .child-2 {
        /* max-height: 100vh; */
        width: 50%;
        margin: 10px;
        border-radius: 10px;
        padding: 10px;
        background-color: #FBEEC1;
    }

    .chat-body-parent {
        display: flex;
        justify-content: center;
        align-items: center;
        /* height: 60vh; */
    }

    .chat-body, .message {
        /* max-height: 100vh; */
        width: 100%;
        background-color: #557A95;
        border-radius: 10px;
        display: flex;      
        padding: 10px;
        flex-direction: column;
    }

    .message {
        max-height: 400px;  /* Or whatever height value you see fit */
        overflow-y: auto;
    }

    .chat-body .message .receive, .send {
        background-color: #B1A296;
        max-width: 400px;
       
        border-radius: 10px;
        padding: 10px;
        margin-bottom: 10px;
    }

    .send:hover {
        padding: 15px;
        transition: 0.8s;
    }

    .receive:hover {
        padding: 15px;
        transition: 0.8s;
    }

    .chat-body .message .send {
        align-self: flex-end;
    }

    .chat-body .message .receive {
        align-self: flex-start;
    }

    form {
        display: flex;
        align-items: center;
        justify-content: space-around;
    }

    form textarea {
        width: 70%;
        height: 40px;
        border-radius: 10px;
        padding: 10px;
    }

    form button {
        width: 25%;
        padding: 10px;
        background-color: #FBEEC1;
        border-radius: 5px;
        border: none;
        color: #000;
    }
    @media only screen and (max-width: 600px) {
    .child-2 {
        width: 100%;
    }
}

</style>
</html>